### ISSUE TITLE
invalid qml singleton

### ISSUE THREAD

**Issue by pr0dukter** [Maldela/fancontrol-gui#13]
was fing around with perfectly good fancontrol_gui reinstalled and believe me ive been battling this all night, save me

qt5ct: using qt5ct plugin
"file:///usr/share/kpackage/genericqml/fancontrol-gui/contents/ui/Application.qml" 
 "Error loading QML file.\n25: plugin cannot be loaded for module \"Fancontrol.Qml\": Invalid QML singleton type name \"base\"; type names must begin with an uppercase letter\n"

**Comment by Maldela** [comment]
See [](https://github.com/Maldela/fancontrol-gui/issues/12)

**Comment by pr0dukter** [comment]
404?

**Comment by pr0dukter** [comment]
also graph is meeeessssed up because in settings graph temps are set to -39.9 each and if i change them it freezes until a  segfault

qt5ct: using qt5ct plugin
pp: Failed to translate a shader for depth1fs
pp: Failed to translate a shader for blend2fs
pp: Failed to translate a shader for color1fs
pp: Failed to translate a shader for blend2fs
"New service name: 'fancontrol'"
"Temp has no label: '/sys/devices/pci0000:00/0000:00:02.0/0000:01:00.0/hwmon/hwmon0/temp1'"
"Temp has no label: '/sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1'"
"Temp has no label: '/sys/devices/platform/it87.552/hwmon/hwmon3/temp1'"
"Temp has no label: '/sys/devices/platform/it87.552/hwmon/hwmon3/temp2'"
"Temp has no label: '/sys/devices/platform/it87.552/hwmon/hwmon3/temp3'"
"Loading config file: '/etc/fancontrol'"
file:///usr/lib/qt/qml/QtQuick/Controls/ToolBar.qml:146:9: QML Item: Binding loop detected for property "layoutHeight"
file:///usr/lib/qt/qml/QtQuick/Controls/ToolBar.qml:146:9: QML Item: Binding loop detected for property "layoutHeight"
file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml:45:14: QML ToolBar: Binding loop detected for property "implicitHeight"
pp: Failed to translate a shader for depth1fs
pp: Failed to translate a shader for blend2fs
pp: Failed to translate a shader for color1fs
pp: Failed to translate a shader for blend2fs
[1]    28050 segmentation fault (core dumped)  fancontrol_gui

**Comment by Maldela** [comment]
The link should work. Just look in the closed issues section for issue #12. The singleton name issue has been fixed.

**Comment by Maldela** [comment]
Fixed the link.

**Comment by pr0dukter** [comment]
yes i can load the gui now but the last page where set fancontrol to startup if i click in the boxes to edit the temp range for graph it locks up

**Comment by Maldela** [comment]
I'm sorry but I can't reproduce your issue. Try editing ~/.config/fancontrol-gui and set MaxTemp and MinTemp in the preferences section manually to your desired values. Keep in mind those values are °C.
If those values do not already exist create them like this:

[preferences]
MaxTemp=90
MinTemp=30

**Comment by pr0dukter** [comment]
thanks that did it, so strange, never had to create them myself before,
must be lm_sensors or sensors3.conf related thanks for all your help ill
close the issue here in a bit

**Comment by pr0dukter** [comment]
thanks for your quick response and caring about youre work, i appreciate it : D !!

**Comment by Maldela** [comment]
You're very welcome.
