### ISSUE TITLE
changing graph temperature range locks to -39.99F

### ISSUE THREAD

**Issue by maxbla** [Maldela/fancontrol-gui#19]
#### Version
```
$ pacman -Qs fancontrol
local/fancontrol-gui-git v0.5.r48.g25c1a50-1
    GUI for the fancontrol script and systemd service
```

#### OS
Arch Linux
```
$ uname -r
4.19.4-arch1-1-ARCH
```
#### Steps to Reproduce 

1. open fancontrol-GUI
2. navigate to settings tab
3. click down arrow on field labeled `Minimum temperature for fan graphs` (you could have clicked either arrow in either temperature boxes)
4. Value in the adjacent box changes to `-39.99°F`
5. Switch to graph tab. Yep, it's actually showing that range of temperatures.

**Comment by Maldela** [comment]
v0.5.r48.g25c1a50-1 seems pretty old. Please try with the current version.

**Comment by Maldela** [comment]
I think I found the problem. Fix will be up shortly.

**Comment by maxbla** [comment]
I think you mentioned I was running an old version (guilty as charged). Just to be clear, in the latest release, the problem is still there.
```
$ pacman -Qs fancontrol
local/fancontrol-gui v0.6-1
    GUI for fancontrol and the fancontrol systemd service
```

**Comment by Maldela** [comment]
Try the fancontrol-gui-git package from AUR. Or clone directly from this repository.

**Comment by maxbla** [comment]
The min/max temperature controls are now working as expected, thanks for the quick fix!
