### ISSUE TITLE
Program refuses to load, Fancontrol.Qml missing

### ISSUE THREAD

**Issue by lilltiger** [Maldela/fancontrol-gui#2]
I did a git clone and compiled but i get this issue when trying to run the app:

"file:///usr/share/kpackage/genericqml/fancontrol-gui/contents/ui/Application.qml" 
 "Error loading QML file.\n25: module \"Fancontrol.Qml\" is not installed\n"

there is no "Fancontrol.Qml" at all on my system.

**Comment by Maldela** [comment]
Have you installed the application with sudo make install? It should install the QML plugin in /usr/lib/qt/qml/Fancontrol/Qml. At least on Arch it does. The path may be different on other distributions.

**Comment by Maldela** [comment]
I changed the qml plugin install dir to be install prefix agnostic. I hope this fixes your problem.

**Comment by xPathin** [comment]
Same issue on Arch, even installing from AUR using the fancontrol-gui-git project.
Here is the output: http://pastebin.com/wMCD1A1B

**Comment by belldandu** [comment]
@Maldela You should really update the packages on the aur

**Comment by Maldela** [comment]
Fixed now. The extra-cmake-modules variable QMLDIR points to /usr/lib/qml but arch looks in /usr/lib/qt/qml for QML plugins. I changed to install in the right location. I hope this doesn't break it for any other distributions.
