### ISSUE TITLE
fancontrol process ends on warning

### ISSUE THREAD

**Issue by jahknem** [Maldela/fancontrol-gui#25]
Hi,

I installed all dependencies per readme. When trying to start fancontrol_gui using terminal I get the following output: 

`Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

Not really sure how to handle this..

This is on Debian 9 Sid.

**Comment by Maldela** [comment]
I'm not really sure where this is coming from. Fancontrol-gui doesn't set any environment variables. Are you running on wayland?

**Comment by jahknem** [comment]
Yes. However that was what was installed during the clean debian install

**Comment by jahknem** [comment]
I just tried it again and got a different error. Process is still running.
```
jan@debian:~$ fancontrol_gui
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n172: Cannot assign to non-existent property \"anchors\"\n"
```

**Comment by Maldela** [comment]
Have you tried setting QT_QPA_PLATFORM=wayland like the warning says?

**Comment by jahknem** [comment]
I've tried googling how, but I can't find it anywhere. Could also not find it in the file specified in the error message

**Comment by Maldela** [comment]
It's an environment variable. Just type `QT_QPA_PLATFORM=wayland fancontrol_gui`.

**Comment by jahknem** [comment]
I tried running it and tried it again with sudo with different results. However I've now set different profiles in the BIOS which works just fine.

```
jan@debian:~$ QT_QPA_PLATFORM=wayland fancontrol_gui
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n172: Cannot assign to non-existent property \"anchors\"\n"
^C
jan@debian:~$ sudo QT_QPA_PLATFORM=wayland fancontrol_gui
[sudo] Passwort für jan: 
error: XDG_RUNTIME_DIR not set in the environment.
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Abgebrochen
```
I'll look at this later and see if by reinstalling the involved applications anything changes. Thanks for the support anyway

**Comment by Maldela** [comment]
This is definately a wayland problem. I'm not sure what to do to make qt applications run on wayland in debian. Maybe you need to install qt5-wayland to run qt apps on wayland.
