### ISSUE TITLE
runtime dependency

### ISSUE THREAD

**Issue by adi87plde** [Maldela/fancontrol-gui#27]
Hello, 
I use xubuntu 18.04 
cmake gives me this error

cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on -DBUILD_PLASMOID=on
-- Found KF5: success (found version "5.44.0") found components:  I18n 
-- qmlplugindump failed for QtQuick.
-- Could NOT find QtQuick-QMLModule (missing: QtQuick-QMLModule_FOUND) 
-- qmlplugindump failed for QtQuick.Controls.
-- Could NOT find QtQuick.Controls-QMLModule (missing: QtQuick.Controls-QMLModule_FOUND) 
-- qmlplugindump failed for QtQuick.Layouts.
-- Could NOT find QtQuick.Layouts-QMLModule (missing: QtQuick.Layouts-QMLModule_FOUND) 
-- qmlplugindump failed for QtQuick.Dialogs.
-- Could NOT find QtQuick.Dialogs-QMLModule (missing: QtQuick.Dialogs-QMLModule_FOUND) 
-- qmlplugindump failed for org.kde.kirigami.
-- Could NOT find org.kde.kirigami-QMLModule (missing: org.kde.kirigami-QMLModule_FOUND) 
-- Compiling for Systemd
-- Build the standalone application
-- Found KF5: success (found version "5.44.0") found components:  CoreAddons DBusAddons Package Declarative Config Notifications 
-- Build the KCM
-- Found KF5: success (found version "5.44.0") found components:  CoreAddons Package Declarative KCMUtils 
-- qmlplugindump failed for org.kde.kcm.
-- Could NOT find org.kde.kcm-QMLModule (missing: org.kde.kcm-QMLModule_FOUND) 
-- Build the plasmoid
-- qmlplugindump failed for org.kde.plasma.core.
-- Could NOT find org.kde.plasma.core-QMLModule (missing: org.kde.plasma.core-QMLModule_FOUND) 
-- Found KF5: success (found version "5.44.0") found components:  Auth Config 
-- The following OPTIONAL packages have been found:

 * KF5WidgetsAddons (required version >= 5.44.0)
 * KF5ConfigWidgets (required version >= 5.44.0)

-- The following REQUIRED packages have been found:

 * Gettext
 * PythonInterp
 * KF5I18n
 * KF5DBusAddons
 * KF5Notifications
 * KF5Declarative
 * KF5KCMUtils
 * Qt5Gui (required version >= 5.7.0)
 * KF5Package (required version >= 5.44.0)
 * Qt5Widgets (required version >= 5.7.0)
 * KF5WindowSystem (required version >= 5.44.0)
 * ECM (required version >= 1.6.0)
 * KF5Plasma
 * Qt5Core
 * Qt5DBus
 * Qt5Network (required version >= 5.9.5)
 * Qt5Qml
 * KF5CoreAddons (required version >= 5.44.0)
 * KF5Auth
 * KF5Config
 * KF5
 * Qt5Test
 * Qt5

**-- The following RUNTIME packages have not been found:**

 * QtQuick-QMLModule, QML module 'QtQuick' is a runtime dependency.
 * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.
 * QtQuick.Layouts-QMLModule, QML module 'QtQuick.Layouts' is a runtime dependency.
 * QtQuick.Dialogs-QMLModule, QML module 'QtQuick.Dialogs' is a runtime dependency.
 * org.kde.kirigami-QMLModule, QML module 'org.kde.kirigami' is a runtime dependency.
 * org.kde.kcm-QMLModule, QML module 'org.kde.kcm' is a runtime dependency.
 * org.kde.plasma.core-QMLModule, QML module 'org.kde.plasma.core' is a runtime dependency.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/adimonn/fancontrol-gui/build

**and does not start**
fancontrol_gui 
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n172: Cannot assign to non-existent property \"anchors\"\n"

**Comment by Maldela** [comment]
Looks like qmlplugindump fails every time. You should open a ticket on the Qt bugtracker.
The runtime error about anchors not existing is weird though. Have you installed all the QML runtime dependencies?

**Comment by Kvalme** [comment]
Same issue on kubuntu 18.10.
Configuration issues seems to be a bug in qmlplugindump.
All modules installed but when i startt fancontrol_gui i got same error:
```
"file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/Application.qml" 
 "Error loading QML file.\n172: Cannot assign to non-existent property \"anchors\"\n"

```

Application stays in process but no ui appears

**Comment by Maldela** [comment]
I just installed an Ubuntu VM and ran into the same error as you. Why this happens is beyond me. On Arch it works flawlessly. But I implemented a workaround. Try again. It should work now.

**Comment by Kvalme** [comment]
Now it starts and I can see window. But I got following output:

```
fancontrol_gui 
"New service name: 'fancontrol'"
"Loading config file: '/etc/fancontrol'"
QFileSystemWatcher::removePaths: list is empty
QQmlComponent: Component is not ready
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/PageRow.qml:606: Error: Error while loading page: file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/PwmFansTab.qml:116 Type Fancontrol.ProfilesDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Fancontrol/Qml/ProfilesDialog.qml:114 Cannot assign to non-existent property "anchors"

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:111: TypeError: Cannot read property 'length' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:111: TypeError: Cannot read property 'length' of null
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:111: TypeError: Cannot read property 'length' of null
QQmlComponent: Component is not ready
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/PageRow.qml:606: Error: Error while loading page: file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/PwmFansTab.qml:116 Type Fancontrol.ProfilesDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Fancontrol/Qml/ProfilesDialog.qml:114 Cannot assign to non-existent property "anchors"

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:111: TypeError: Cannot read property 'length' of null

```

And "fans" tab completely empty. (see attachment)
I beleive that I used fancontrol_gui on previous (18.04) ubuntu version with same hw.
![fancontrol](https://user-images.githubusercontent.com/3676901/55639617-7b9ac500-57d2-11e9-9dab-3f847751c1dc.jpg)

**Comment by Maldela** [comment]
I forgot the profiles dialog. Fixed now.

**Comment by Kvalme** [comment]
I tryed updated version but still no luck.
```
file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/PageRow.qml:606: Error: Error while loading page: file:///usr/share/kpackage/genericqml/org.kde.fancontrol.gui/contents/ui/PwmFansTab.qml:116 Type Fancontrol.ProfilesDialog unavailable
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Fancontrol/Qml/ProfilesDialog.qml:114 Cannot assign to non-existent property "anchors"

file:///usr/lib/x86_64-linux-gnu/qt5/qml/org/kde/kirigami.2/ContextDrawer.qml:111: TypeError: Cannot read property 'length' of null

```

**Comment by Maldela** [comment]
Please try again. I scanned the code for other dialog anchors and removed them all. This should be it.

**Comment by Kvalme** [comment]
Looks like issue is gone. Now i can see fan tab. Thanks!

**Comment by Maldela** [comment]
Great!

**Comment by arm3nyn** [comment]
still same issue in ubuntu 18.04 runtime dependency
-- The following RUNTIME packages have not been found:

 * QtQuick-QMLModule, QML module 'QtQuick' is a runtime dependency.
 * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.
 * QtQuick.Layouts-QMLModule, QML module 'QtQuick.Layouts' is a runtime dependency.
 * QtQuick.Dialogs-QMLModule, QML module 'QtQuick.Dialogs' is a runtime dependency.
 * org.kde.kirigami-QMLModule, QML module 'org.kde.kirigami' is a runtime dependency.
 * org.kde.kcm-QMLModule, QML module 'org.kde.kcm' is a runtime dependency.
 * org.kde.plasma.core-QMLModule, QML module 'org.kde.plasma.core' is a runtime dependency.

**Comment by Maldela** [comment]
> still same issue in ubuntu 18.04 runtime dependency
> -- The following RUNTIME packages have not been found:
> 
> * QtQuick-QMLModule, QML module 'QtQuick' is a runtime dependency.
> * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.
> * QtQuick.Layouts-QMLModule, QML module 'QtQuick.Layouts' is a runtime dependency.
> * QtQuick.Dialogs-QMLModule, QML module 'QtQuick.Dialogs' is a runtime dependency.
> * org.kde.kirigami-QMLModule, QML module 'org.kde.kirigami' is a runtime dependency.
> * org.kde.kcm-QMLModule, QML module 'org.kde.kcm' is a runtime dependency.
> * org.kde.plasma.core-QMLModule, QML module 'org.kde.plasma.core' is a runtime dependency.

If the app works, just ignore those. If it doesn't work, you are missing some packages.
