### ISSUE TITLE
Fans detect problem in Fans view gui

### ISSUE THREAD

**Issue by manujose94** [Maldela/fancontrol-gui#31]
Please, excuse my english. It is a work in progress.

I try to view my fans but arise one problem. It show this text:

There are no pwm capable fans in your system. Try running 'sensrod-dectect' in a terminal and restar this aplication.

Actualy, I using Ubuntu 19.04:

5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Maldela** [comment]
It means that lm-sensors has not detected any compatible sensors on your system. Maybe this link is helpful [https://askubuntu.com/questions/53762/how-to-use-lm-sensors](url)

**Comment by manujose94** [comment]
> It means that lm-sensors has not detected any compatible sensors on your system. Maybe this link is helpful [https://askubuntu.com/questions/53762/how-to-use-lm-sensors](url)

Grateful for the prompt reply.
The problem  may to due  to: "There are no pwm-capable sensors" then you must use profile laptop exlusive.

In my case: https://askubuntu.com/questions/783069/fan-control-on-msi-laptop-no-pwm-capable-sensors

**Comment by Maldela** [comment]
I'm not sure I can help you with that. Fancontrol-GUI is only a frontend for configuring the fancontrol script. You seem to have a problem with lm-sensors or a kernel module.
