### ISSUE TITLE
Compiling on Fedora successful, but missing runtime package error occurs

### ISSUE THREAD

**Issue by win8linux** [Maldela/fancontrol-gui#33]
When attempting to compile `fancontrol-gui` on Fedora 31, CMake shows this error:
```
-- The following RUNTIME packages have not been found:

 * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.
```

The command used to install the requirements:
```
sudo dnf install qt5-devel kf5-ki18n-devel kf5-kauth-devel kf5-kconfig-devel kf5-kpackage-devel kf5-kcoreaddons-devel kf5-kdbusaddons-devel extra-cmake-modules kf5-knotifications-devel qt5-qtquickcontrols2-devel kf5-kconfigwidgets-devel kf5-kcmutils-devel kf5-plasma-devel cmake gettext qt5-qtbase-devel gcc-c++ kf5-kdeclarative-devel qt5-qtquickcontrols qt5-qtquickcontrols2
```

In any case, the application seems to run just fine anyways and I've created PR https://github.com/Maldela/fancontrol-gui/pull/32 for adding the necessary command to install the requirements on Fedora.

**Comment by Maldela** [comment]
This seems to be a bug in qmlplugindump. I have the same problem on Arch.
Thanks for the PR.

**Comment by FoxxMD** [comment]
@Maldela can you provide the requirements install command for arch? yay/pacman?
