### ISSUE TITLE
Feature Request: Just Use Celsius

### ISSUE THREAD

**Issue by billop** [Maldela/fancontrol-gui#35]
I feel like there's no reason to ever want to see Fahrenheit temperatures when looking at the temperatures of computer components. I think it makes more sense for this application to just stick to Celsius so that users with locale of `en_US` don't have to mess with their locale just for one application.

**Comment by Maldela** [comment]
That's probably a good idea. The whole temperature conversion is just a potential source for errors anyway.

**Comment by Maldela** [comment]
Just pushed a new commit that removes Fahrenheit and Kelvin units. Let me know, if you encounter any problems.

**Comment by billop** [comment]
Seems good to me, thanks a lot.
