### ISSUE TITLE
Windows opens at zero size and all controls are "squished".

### ISSUE THREAD

**Issue by BloodBlight** [Maldela/fancontrol-gui#36]
After first run, a window is opened, but it is zero in X and Y size. Resizing it shows some data squished in, but is unusable.

It does appear to remember window sizes on restart, but all of the controls are still broken.

PastBin from fancontrol_gui:
https://pastebin.com/R0QrTzHe

Image from UI:
https://imgur.com/a/aBlGh4c

Config file [~/.config/fancontrol-gui]:
```
[window]
Height 1600=412
Width 2560=445
```

**Comment by Maldela** [comment]
This looks like a problem with qml or kirigami. Do other kirigami based apps work for you?

**Comment by BloodBlight** [comment]
Sure enough, I installed kirigami-gallery and it looks almost identical.

**Comment by BloodBlight** [comment]
Looks like they have their "Issues" area disabled... :/
