### ISSUE TITLE
Could NOT find QtQuick.Controls-QMLModule (missing: QtQuick.Controls-QMLModule_FOUND) 

### ISSUE THREAD

**Issue by sildeag** [Maldela/fancontrol-gui#39]
I am using Ubuntu 20.04 and following the instructions given after installing all the dependencies and then:
`git clone https://github.com/Maldela/fancontrol-gui.git`
`cd fancontrol-gui`
`mkdir build`
`cd build` 
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on -DBUILD_PLASMOID=on`
results is
`Could NOT find QtQuick.Controls-QMLModule (missing: QtQuick.Controls-QMLModule_FOUND) `
and
`QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.`
what am I missing?

**Comment by Qiangong2** [comment]
Well... It looks like you're probably missing QtQuick Controls

**Comment by sildeag** [comment]
Yes it does, however it was installed just not detected.  `sudo apt-get install qml-module-qtquick-controls2`.  I also did  `sudo apt-get install qtquickcontrols2-5-dev`.  The issue mentions this is just used at runtime and Fancontrol-GUI does work, sort of.

**Comment by Maldela** [comment]
This is a bug in qmldump. Just ignore it.
