### ISSUE TITLE
Please provide screenshots

### ISSUE THREAD

**Issue by protist** [Maldela/fancontrol-gui#40]
I'm considering installing fancontrol-gui, but I'd like to get a sense of what it provides above `fancontrol`. I can see a lot of information in the README about building and installing, but not much on what functionality is provided. Screenshots would be a concise way of showing what is possible.

**Comment by fikrimi23** [comment]
here is all the menu available
(Arch linux, i3wm, using fancontrol, on ASUS GL552JX)

![image](https://user-images.githubusercontent.com/8409391/89116324-02da7480-d4bd-11ea-867c-3172edf87f2e.png)

![image](https://user-images.githubusercontent.com/8409391/89116322-f8b87600-d4bc-11ea-89e4-515121cd7d71.png)

![image](https://user-images.githubusercontent.com/8409391/89116328-0a9a1900-d4bd-11ea-955f-f4e80c885d8b.png)

![image](https://user-images.githubusercontent.com/8409391/89116329-108ffa00-d4bd-11ea-990c-2c1f2ca3dc90.png)

**Comment by protist** [comment]
Brilliant. Thank you @fikrimi23. This would be perfect in the README!

**Comment by protist** [comment]
Thank you @Maldela and @fikrimi23. Looks great! I'm also enjoying the program itself now. Well done and thanks again!
