### ISSUE TITLE
How to launch? (I have installed).

### ISSUE THREAD

**Issue by DimitriBolt** [Maldela/fancontrol-gui#43]
Hi, I have installed, and What do I have to do now? Thanks.

**Comment by DimitriBolt** [comment]
comment: There are no executable files.

**Comment by fikrimi23** [comment]
isn't there a bin folder ?

**Comment by Maldela** [comment]
If you have installed with `sudo make install`, you should have a menu entry in your application launcher.
Alternatively typing `fancontrol_gui` in the terminal will do the job.
The executable is located in 'fancontrol-gui' in your build folder.
