### ISSUE TITLE
 RUNTIME packages have not been found

### ISSUE THREAD

**Issue by yyagin** [Maldela/fancontrol-gui#44]
I got a error when i did cmake on Ubuntu 18.04 and Fancontrol-GUI opens but nothing in the screen. I add an attachment below.
I try the reinstall the packages but it seems all are already installed.
-- The following RUNTIME packages have not been found:

 * QtQuick-QMLModule, QML module 'QtQuick' is a runtime dependency.
 * QtQuick.Controls-QMLModule, QML module 'QtQuick.Controls' is a runtime dependency.
 * QtQuick.Layouts-QMLModule, QML module 'QtQuick.Layouts' is a runtime dependency.
 * QtQuick.Dialogs-QMLModule, QML module 'QtQuick.Dialogs' is a runtime dependency.
 * org.kde.kirigami-QMLModule, QML module 'org.kde.kirigami' is a runtime dependency.
 * org.kde.kcm-QMLModule, QML module 'org.kde.kcm' is a runtime dependency.
 * org.kde.plasma.core-QMLModule, QML module 'org.kde.plasma.core' is a runtime dependency.

![image](https://user-images.githubusercontent.com/16089402/90316335-26280980-df2a-11ea-9fe9-e11f722d6f26.png)

**Comment by Maldela** [comment]
Try starting fancontrol_gui from the terminal and tell me if it prints any error messages.
