### ISSUE TITLE
Fancontrol-Gui/LM-sensor doesn't seem to install fancontrol "service" Ubuntu 20.04 

### ISSUE THREAD

**Issue by JoneKone** [Maldela/fancontrol-gui#46]
So, i tried multiple times to "enable service" and start service on the GUI but it didn't seem to do anything. just took a long time and then continued.

Finally after trying to figure out where is this fancontrol service, I did apt search fancontrol and there it was, so I installed it.

https://hastebin.com/qapiraduke.sql
Still doesn't work.

Yes I'm a newb :) I just can't make heads or tails of this, it worked on my old install ubuntu 19.10 but for some reason I haven't gotten it to work on any ubuntu 20.04 installs. I copypasted all the instructions from readme.

So just now, at time of writing I removed the /etc/fancontrol file and it still says "some settings missing" failing to start.

**Comment by JoneKone** [comment]
https://hastebin.com/ehasumujod.coffeescript

**Comment by Maldela** [comment]
Don't remove the `/etc/fancontrol` file. You need to configure at least one of your fans with either `fancontrol_gui` or `pwmconfig`. A `/etc/fancontrol` configuration file without at least one configured fan will get rejected by the `fancontrol` service.

**Comment by JoneKone** [comment]
Well it works now, honestly i don't know what changed maybe reboot.
