### ISSUE TITLE
Fan Controls not saving Nor Applying

### ISSUE THREAD

**Issue by lbibass** [Maldela/fancontrol-gui#49]
Whenever I generate fan profiles, they do not work. There is no change in the fanspeed. upon reboot, all the profiles are lost and /etc/fancontrol is erased and rewritten. No idea what is going on. Ubuntu 20.10, Asus X570-i gaming.

**Comment by Maldela** [comment]
Please start the app from terminal and tell me what the output is when you press the apply button.

**Comment by lbibass** [comment]
I'm trying to start the app from the terminal, but it keeps saying Fancontrol-GUI: Command not found.

**Comment by Maldela** [comment]
The binary name is `fancontrol_gui`

**Comment by lbibass** [comment]
> The binary name is `fancontrol_gui`

Thank you! Actually, it seems to be working now? Not sure what issue I was having before. Thanks for the tip. 

By the way, do you think you could add more points for adjustment? Two seems a little... limited.

**Comment by Maldela** [comment]
The two points are a limitation of the fancontrol script, which is not part of this project. But I'm working on a replacement for that with much more funcionality.

**Comment by lbibass** [comment]
Alright, cool. One other thing though, is that the fan controls and profiles aren't saving across restarts. I've saved a profile, but every time I reboot it gets reset and I can't access it anymore. Do you have any ideas?

**Comment by Maldela** [comment]
Does the profile survive if you close the app and start it again?

**Comment by lbibass** [comment]
> Does the profile survive if you close the app and start it again?

yes, the profile stays. It only has an issue if I reboot into windows, and then boot back. Then I get an error message saying "Invalid Temp Entry: '(then it's some sensor, it changes every time)'

Then my profile is erased.

**Comment by Maldela** [comment]
Seems like you are running into [this](https://wiki.archlinux.org/index.php/Fan_speed_control#Device_Paths_have_Changed_in_/etc/fancontrol) problem.
Every time this happens your profiles become invalid.
This will be fixed in my fancontrol replacement later.

**Comment by lbibass** [comment]
Ah, alright! Thanks for the help!
