### ISSUE TITLE
Fans not detected

### ISSUE THREAD

**Issue by Cody-G** [Maldela/fancontrol-gui#5]
Thanks for your work! It builds and starts fine for me.  However it doesn't detect any PWM fans in my system, even after telling it to check again (and I know there are 4 PWM case fans + 2 CPU fans).  The temperature sensing is working well.  My system:

Ubuntu 16.04
motherboard: Asrock EP2C602-4L/D16
default, distro-provided lm_sensors and fancontrol packages

**Comment by Cody-G** [comment]
I'm pretty certain now that this is low-level issue with linux's ability to monitor my PWM fans:  When I run ``sudo /usr/sbin/pwmconfig`` I get nothing.  Do you agree?

**Comment by Maldela** [comment]
I agree. Maybe your Motherboard isn't supported although i'm not an expert on the low level stuff.

**Comment by Cody-G** [comment]
Got it, thanks!
