### ISSUE TITLE
[Ubuntu 20.10] Error on cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on -DBUILD_PLASMOID=on

### ISSUE THREAD

**Issue by srdtrk** [Maldela/fancontrol-gui#50]
I've recently reinstalled my OS (from Ubuntu 20.04). I was able to build this before but now it gives me the following error:

Installing in /usr. Run /home/srdtrk/build/fancontrol-gui/build/prefix.sh to set the environment for fancontroller.
CMake Error at /usr/share/ECM/modules/ECMQueryQmake.cmake:30 (message):
  No qmake Qt5 binary found.  Can't check QT_INSTALL_BINS as required
Call Stack (most recent call first):
  build/FindQtQuick-QMLModule.cmake:10 (query_qmake)
  /usr/share/ECM/modules/ECMQMLModules.cmake:42 (find_package)
  CMakeLists.txt:58 (ecm_find_qmlmodule)

-- Configuring incomplete, errors occurred!

**Comment by Maldela** [comment]
Looks like ECM can't find qmake on your system. Qmake should be part of qt5-base/core.
