### ISSUE TITLE
Asus p6t fan full speed 

### ISSUE THREAD

**Issue by daniele777** [Maldela/fancontrol-gui#58]
Hi!!! I'll try to control fan speed of asus p6t but i have full speed what can i do??? THX
![Cattura schermo_seleziona-area_20210328133935](https://user-images.githubusercontent.com/8341788/112750818-177af800-8fcb-11eb-834c-f2d2b4ef625e.png)
![Cattura schermo_seleziona-area_20210328133951](https://user-images.githubusercontent.com/8341788/112750820-19dd5200-8fcb-11eb-9651-cd68f6146ae0.png)

**Comment by Maldela** [comment]
Have you tried running `sensors-detect`? If you have you should ask the lm-sensors people for help. Fancontrol-GUI is just a gui for fancontrol which uses lm-sensors for controlling your fans.

**Comment by daniele777** [comment]
Solved by manager from BIOS !!
