### ISSUE TITLE
PWMEnable Cannot exceed 0-2!

### ISSUE THREAD

**Issue by ibrokemypie** [Maldela/fancontrol-gui#6]
Whenever I launch I get that error both in terminal and in a pop up. Afterwards there are no errors, but cannot actually change fan speeds and the fan speed tests run forever.

**Comment by Maldela** [comment]
I can't reproduce your issue right now, because i upgraded to a AMD Ryzen board recently which isn't supported by lm_sensors right now. But I wanted to build a small HTPC with my old board some time this week. I'll see what I can do when that's finished.

**Comment by Maldela** [comment]
I just made some changes to the master branch. Try it again and see if the problem still persists.

**Comment by ibrokemypie** [comment]
Seems all good now, thanks!
