### ISSUE TITLE
KDE Deps

### ISSUE THREAD

**Issue by ibrokemypie** [Maldela/fancontrol-gui#7]
I truly love this app, there are no alternatives, however I do not use KDE and generally avoid KDE programs due to the massive dependencies, and this seems to require a lot. Is it at all possible to achieve the same without KDE deps?

**Comment by maxbla** [comment]
This is a gui frontend to fancontrol ([debian package](https://packages.debian.org/stretch/fancontrol), [arch package](https://www.archlinux.org/packages/extra/x86_64/lm_sensors/)). If you don't want qt dependencies, you can install the fancontrol package and mess with config files by hand. You can find some instructions [here](https://wiki.archlinux.org/index.php/Fan_speed_control#Fancontrol_(lm-sensors)) and in fancontrol's manpage.

If you don't have Qt programs, the first one will install loads of dependencies and if you don't have GTK+ apps, the first one will install loads of dependencies, but each program has to pick one or the other.

Also this should probably be closed as wontfix.
