### ISSUE TITLE
CMake configuration error (package configuration file)

### ISSUE THREAD

**Issue by win8linux** [Maldela/fancontrol-gui#8]
Hello there! I'm trying to compile fancontrol-gui on Linux Mint 18 KDE and I keep encountering this issue:
```
▶ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on
CMake Error at CMakeLists.txt:37 (find_package):
  By not providing "FindECM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ECM", but
  CMake did not find one.

  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/*********/Public/fancontrol-gui/build/CMakeFiles/CMakeOutput.log".
```
Here's the [CMakeOutput.log](https://github.com/Maldela/fancontrol-gui/files/1535458/CMakeOutput.log) for further reference.

There was an `ecm` package that I installed after the first encounter with this error. Unfortunately, it still persists.

**Comment by Maldela** [comment]
Looks like you don't have extra-cmake-modules installed.

**Comment by win8linux** [comment]
I've just installed `extra-cmake-modules` and now this appears:
```
▶ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on
CMake Error at CMakeLists.txt:42 (find_package):
  By not providing "FindQt5Core.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Core", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/home/julius/Public/fancontrol-gui/build/CMakeFiles/CMakeOutput.log".
```
along with the updated [CMakeOutput.log](https://github.com/Maldela/fancontrol-gui/files/1535496/CMakeOutput.log) file.

I did attempt to remedy this error by installing next `qt5-qmake`, but to no avail on the next attempt.

**Comment by Maldela** [comment]
You also need the qtbase5-dev package. Look for the *-dev package on Debian derivatives like Ubuntu and Mint every time a package is missing.

**Comment by win8linux** [comment]
Intalled `qtbase5-dev` and `kdelibs5-dev` to be safe and...
```
▶ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:74 (find_package):
  Could not find a package configuration file provided by "KF5I18n" with any
  of the following names:

    KF5I18nConfig.cmake
    kf5i18n-config.cmake

  Add the installation prefix of "KF5I18n" to CMAKE_PREFIX_PATH or set
  "KF5I18n_DIR" to a directory containing one of the above files.  If
  "KF5I18n" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:46 (find_package)


-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find KF5 (missing: I18n)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:46 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/*********/Public/fancontrol-gui/build/CMakeFiles/
[CMakeOutput.log](https://github.com/Maldela/fancontrol-gui/files/1535527/CMakeOutput.log)
".
```
Dang it.

**Comment by Maldela** [comment]
You need a lot more packages than just qtbase5-dev ;-) Look for kf5i18n-dev or libkf5i18n-dev or something like that. Not sure what the exact name is. Furthermore you need the kf5 declarative, config, coreaddons and package packages. And maybe some others. The error messages will tell you what to install.

**Comment by win8linux** [comment]
Ok, then. I'll do some trial-and-error for a bit until it works. I'd suggest a compilation guide (or a dependency list/equivalent at least) for the future since it seems that not too many distributions have this packaged up.

**Comment by coreybruce** [comment]
Maybe in future you should do a better job of telling users what dependencies they need to install before making this..

can you tell me everything I need to run this please?

**Comment by Maldela** [comment]
Extra-Cmake-Modules.
Qt5: Base/Core, Widgets, GUI, QML.
KF5: I18n, Auth, Config, Package, Declarative, CoreAddons, KCMUtils.
The exact package names are different from distro to distro.

**Comment by coreybruce** [comment]
I recommend focusing on Ubuntu first than add other distro dependencies after you have it right on Ubuntu

I have installed a couple of them but it would be much more easier if you could list the actual package names needed on Ubuntu based systems.

**Comment by Maldela** [comment]
I don't run Ubuntu, so I can't test what packages are needed. If you provide me with a list of packages that worked for you, I can put that in the readme.

**Comment by win8linux** [comment]
Here's the `apt` command I used to pull in all of the required packages for building fancontrol-gui:
`sudo apt install libkf5config-dev libkf5auth-dev libkf5package-dev libkf5declarative-dev libkf5coreaddons-dev libkf5kcmutils-dev libkf5i18n-dev libqt5core5a libqt5widgets5 libqt5gui5 libqt5qml extra-cmake-modules`

**Comment by win8linux** [comment]
Confirming successful build and run of fancontrol-gui:
![image](https://user-images.githubusercontent.com/11584387/33778338-2f655b94-dc83-11e7-9186-2ad9778fa77e.png)

However, the fancontrol KCM module crashes soon after this appears when clicking on the empty area:
![image](https://user-images.githubusercontent.com/11584387/33778413-710c15d8-dc83-11e7-8755-b062c4fa8e28.png)

**Comment by Maldela** [comment]
Thanks for testing! KCM should work now. Unfortunately I can't test much of the app myself since I switched to a Ryzen system. But support will hopefully be integrated in the 4.15 kernel. Fancontrol-GUI will get some much needed love then.

**Comment by win8linux** [comment]
Tested the new code for KCM and it works:
![image](https://user-images.githubusercontent.com/11584387/33793863-e55ad772-dcfa-11e7-9078-89b7a665a16a.png)

Closing this issue now.

**Comment by coreybruce** [comment]
Awesome thanks so much also you may want to add QtQuick.Dialogs, lm-sensors and fancontrol to the dependency list also note to the user will want to follow this

https://iandw.net/2014/10/12/fancontrol-under-ubuntu-14-04-resolving-usrsbinpwmconfig-there-are-no-pwm-capable-sensor-modules-installed/

Question tho how do I change speeds on fans on the fly, still learning your application so bear with me

**Comment by win8linux** [comment]
> ...you may want to add QtQuick.Dialogs, lm-sensors and fancontrol to the dependency list...

I think that `QtQuick.Dialogs` is included in QML; please correct me if I'm wrong there. As for `lm-sensors` and `fancontrol`, it's generally assumed that a user or dev building this software would already have those installed.

> ...also note to the user will want to follow this
> 
> https://iandw.net/2014/10/12/fancontrol-under-ubuntu-14-04-resolving-usrsbinpwmconfig-there-are-no-pwm-capable-sensor-modules-installed/

This would probably be better reserved for a wiki instead of the readme, possibly one in the future here on GitHub or on a distro's wiki such as the ArchWiki.

**Comment by Cat22** [comment]
This is impossible to find the depend4encies on opensuse - I have wasted several hours trying to get this fool thing to compile and i cant get the dependencies met. All I wanted to do was to write an iso file to a usb key and instead i ended up down this rat hole
