### ISSUE TITLE
Install guide dosent work.

### ISSUE THREAD

**Issue by huuxfluux** [Maldela/fancontrol-gui#81]
I'm running Pop!_OS 22.04 LTS and i followed the guide.

When running :
` $ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_KCM=on -DBUILD_PLASMOID=on`

I get: 
`CMake Error: The source directory "/home/usr" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by OttomanZ** [comment]
Hi Any update on this I'm facing the same issue here.
